[emacs-yatex]
src.git="https://github.com/hiroseyuuji/yatex"
src.branch="master"
fetch.github='hiroseyuuji/yatex'

[emacs-nano-modeline]
src.git="https://github.com/rougier/nano-modeline"
src.branch="master"
fetch.github="rougier/nano-modeline"

[dpp-vim]
src.git="https://github.com/Shougo/dpp.vim"
src.branch="main"
fetch.github="Shougo/dpp.vim"

[dpp-ext-toml]
src.git="https://github.com/Shougo/dpp-ext-toml"
src.branch="main"
fetch.github="Shougo/dpp-ext-toml"

[dpp-ext-lazy]
src.git="https://github.com/Shougo/dpp-ext-lazy"
src.branch="main"
fetch.github="Shougo/dpp-ext-lazy"

[dpp-ext-installer]
src.git="https://github.com/Shougo/dpp-ext-installer"
src.branch="main"
fetch.github="Shougo/dpp-ext-installer"

[dpp-protocol-git]
src.git="https://github.com/Shougo/dpp-protocol-git"
src.branch="main"
fetch.github="Shougo/dpp-protocol-git"

[yaskkserv2]
src.github="wachikun/yaskkserv2"
# src.branch="master"
fetch.github="wachikun/yaskkserv2"
# cargo_locks = ["Cargo.lock"]

[cargo-compete]
src.github='qryxip/cargo-compete'
fetch.github="qryxip/cargo-compete"
src.branch="master"
# cargo_locks = ["Cargo.lock"]

[emacs-yaml-mode]
src.git="https://github.com/yoshiki/yaml-mode"
src.branch="master"
fetch.github="yoshiki/yaml-mode"

[emacs-dmacro]
src.git="https://github.com/emacs-jp/dmacro"
src.branch='master'
fetch.github='emacs-jp/dmacro'

[emacs-instant-maximized-window]
src.git="https://github.com/blue0513/instant-maximized-window/"
src.branch='master'
fetch.github='blue0513/instant-maximized-window'

[emacs-typst-ts-mode]
src.git="https://github.com/Ziqi-Yang/typst-ts-mode"
src.branch='main'
fetch.github="Ziqi-Yang/typst-ts-mode"


[fish-autols]
src.git="https://github.com/yuys13/fish-autols"
src.branch="main"
fetch.github="yuys13/fish-autols"

[fish-ghq-fzf]
src.git="https://github.com/yuys13/fish-ghq-fzf"
src.branch="main"
fetch.github="yuys13/fish-ghq-fzf"

[fish-cdf]
src.git="https://github.com/yuys13/fish-cdf"
src.branch="main"
fetch.github="yuys13/fish-cdf"

[fish-fzf-bd]
src.git="https://github.com/yuys13/fish-fzf-bd"
src.branch="main"
fetch.github="yuys13/fish-fzf-bd"

[fish-gcd]
src.git="https://github.com/yuys13/fish-gcd"
src.branch="main"
fetch.github="yuys13/fish-gcd"

[mocword]
src.git="https://github.com/high-moctane/mocword"
src.branch="main"
fetch.github="high-moctane/mocword"

