[[plugins]]
repo = 'vim-denops/denops.vim'
# hook_add='''
# let g:denops_server_addr = '127.0.0.1:32123'
# '''

[[plugins]]
repo = 'vim-denops/denops-shared-server.vim'

[[plugins]]
repo = 'Shougo/dpp.vim'

[[plugins]]
repo = 'Shougo/dpp-ext-lazy'
on_source = 'dpp.vim'

[[plugins]]
repo = 'Shougo/dpp-ext-toml'
on_source = 'dpp.vim'

[[plugins]]
repo = 'Shougo/dpp-ext-local'
on_source = 'dpp.vim'

[[plugins]]
repo = 'Shougo/dpp-ext-installer'
on_source = 'dpp.vim'

[[plugins]]
repo = 'Shougo/dpp-protocol-git'
on_source = 'dpp.vim'

[[plugins]]
repo="Shougo/dpp-ext-local"
on_source='dpp.vim'

