# [[plugins]]
# repo = "neovim/nvim-lspconfig"
# on_event = ['BufNewFile', 'BufRead']

# [[plugins]]
# repo = 'williamboman/mason.nvim'
# on_event = ['BufNewFile', 'BufRead']
# hooks_file="$BASE_DIR/rc/hooks/mason.lua"


# [[plugins]]
# repo = "williamboman/mason-lspconfig.nvim"
# on_event = ['BufNewFile', 'BufRead']
# on_source = 'mason.nvim'


[[plugins]]
repo = "nvimtools/none-ls.nvim"
on_event = ['BufNewFile', 'BufRead']
hooks_file="$BASE_DIR/rc/hooks/none_ls.lua"

# [[plugins]]
# repo = 'ray-x/lsp_signature.nvim'
# on_event = ['BufNewFile', 'BufRead']
# depends='nvim-lspconfig'
# lua_source='''
# require('lsp_signature').setup()
# '''
