[[plugins]]
repo='Shougo/ddc.vim'
on_event = ['InsertEnter', 'CmdlineEnter']
hooks_file="$BASE_DIR/lua/ddc.lua"

[[plugins]]
on_souce='ddc.vim'
repo="Shougo/pum.vim"

# [[plugins]]
# repo="github/copilot.vim"
# on_source="ddc.vim"
# hook_source='''
# let g:copilot_no_maps = v:true
# let g:copilot_hide_during_completion = 0
# imap <silent><expr> <C-g> copilot#Accept()
# '''

[[plugins]]
repo="Shougo/ddc-nvim-lsp"
on_source="ddc.vim"

[[plugins]]
repo="Shougo/ddc-source-around"
on_source="ddc.vim"

[[plugins]]
repo="LumaKernel/ddc-file"
on_source="ddc.vim"

[[plugins]]
repo="matsui54/ddc-buffer"
on_source="ddc.vim"

[[plugins]]
repo="Shougo/ddc-source-cmdline"
on_source="ddc.vim"

[[plugins]]
repo="Shougo/ddc-source-mocword"
on_source="ddc.vim"

[[plugins]]
repo='high-moctane/mocword-data'

[[plugins]]
repo="Shougo/ddc-source-cmdline-history"
on_source="ddc.vim"

[[plugins]]
repo="Shougo/ddc-source-lsp"
on_source="ddc.vim"

[[plugins]]
repo='Shougo/ddc-source-copilot'
on_source="ddc.vim"

[[plugins]]
repo="uga-rosa/ddc-source-nvim-lua"
on_source="ddc.vim"

[[plugins]]
repo="LumaKernel/ddc-source-file"
on_source="ddc.vim"

[[plugins]]
repo='Shougo/ddc-source-omni'
on_source = ["ddc.vim", 'vimtex']

[[plugins]]
repo="Shougo/ddc-filter-sorter_rank"
on_source="ddc.vim"

[[plugins]]
repo="Shougo/ddc-ui-pum"
depends = 'pum.vim'
on_source="ddc.vim"

[[plugins]]
repo="Shougo/ddc-ui-native"
on_source="ddc.vim"

[[plugins]]
repo="Shougo/ddc-converter_remove_overlap"
on_source="ddc.vim"

[[plugins]]
repo="tani/ddc-fuzzy"
on_source="ddc.vim"

[[plugins]]
repo="Shougo/ddc-filter-matcher_head"
on_source="ddc.vim"

[[plugins]]
repo="tani/ddc-path"
on_source="ddc.vim"

[[plugins]]
repo="Shougo/ddc-filter-converter_truncate_abbr"
on_source="ddc.vim"

[[plugins]]
repo="lambdalisue/guise.vim"
on_source="ddc.vim"

[[plugins]]
repo="uga-rosa/ddc-previewer-floating"
on_source="ddc.vim"

[[plugins]]
repo="vim-skk/skkeleton"
on_source='ddc.vim'
hooks_file="$BASE_DIR/lua/skk.lua"

[[plugins]]
repo = 'keimoriyama/skkeleton-azik-kanatable'
# rev = 'feature/delete-some-mappings'
on_source = 'skkeleton'


[[plugins]]
repo="skk-dev/dict"

[[plugins]]
repo = "uga-rosa/denippet.vim"
on_source = "ddc.vim"
hooks_file="$BASE_DIR/lua/denippet.lua"

[[plugins]]
repo="delphinus/skkeleton_indicator.nvim"
on_source="ddc.vim"
lua_source="""
require("skkeleton_indicator").setup()
"""
