[[plugins]]
repo="windwp/nvim-autopairs"
on_event = ['InsertEnter']
lua_source='''
require("nvim-autopairs").setup({ disable_filetype = { "vim" }})
'''

[[plugins]]
repo="shellRaining/hlchunk.nvim"
on_event = ["BufReadPre", "BufNewFile"]
lua_source='''
require("hlchunk").setup({
	chunk = {
		enable = true
	},
	indent = {
		enable = true
	},
	line_num = {
		enable = true
	},
	blank = {
		enable = true
	}
})
'''

[[plugins]]
repo = "hrsh7th/nvim-insx"
on_event = ['InsertEnter']
hooks_file="$BASE_DIR/lua/insx_config.lua"

[[plugins]]
repo="kylechui/nvim-surround"
on_map = ['y', 'd']
lua_source='''
require("nvim-surround").setup()
'''

[[plugins]]
repo="mattn/vim-sonictemplate"
on_cmd='Template'
lua_source='''
vim.g.sonictemplate_key = 0
vim.g.sonictemplate_intelligent_key = 0
vim.g.sonictemplate_postfix_key = 0
vim.g.sonictemplate_vim_template_dir = "~/dotfiles/home-manager/programs/neovim/nvim/template/"
'''

[[plugins]]
repo="nvim-treesitter/nvim-treesitter"
on_event = ["BufRead", "CursorHold"]
rev='main'
hook_post_update='TSUpdate'
hooks_file="$BASE_DIR/lua/treesitter.lua"

[[plugins]]
repo='nvim-treesitter/nvim-treesitter-context'
on_event = ["BufReadPre", "BufNewFile"]
depends='nvim-treesitter'
lua_source='''
require('treesitter-context').setup({
	enable = true,
	min_window_height = 20,
})
'''
[[plugins]]
repo="nvim-treesitter/nvim-treesitter-textobjects"
on_event = ["BufReadPre", "BufNewFile"]
depends='nvim-treesitter'
rev='main'

[[plugins]]
repo = 'monaqa/nvim-treesitter-clipping'
depends = ['nvim-treesitter', 'vim-partedit']
on_lua = 'nvim-treesitter-clipping'
lua_add = '''
vim.api.nvim_create_autocmd("FileType", {
  pattern = { "toml", "markdown" },
  callback = function()
	vim.keymap.set("n", "<C-p>", function()
	  require("nvim-treesitter-clipping").clip()
	  vim.keymap.set("n", "Q", "<Cmd>w<CR><Cmd>ParteditEnd<CR>", { buffer = true })
	end, { buffer = true })
  end,
})
'''

[[plugins]]
repo="JoosepAlviste/nvim-ts-context-commentstring"
on_event = ["BufReadPre", "BufNewFile"]
depends='nvim-treesitter'

[[plugins]]
repo="kana/vim-smartword"
on_map = ['w', 'b', 'e']
lua_source='''
vim.keymap.set("n", "w", "<Plug>(smartword-w)")
vim.keymap.set("n", "b", "<Plug>(smartword-b)")
vim.keymap.set("n", "e", "<Plug>(smartword-e)")
'''

[[plugins]]
repo='lambdalisue/gin.vim'
on_cmd = ["GinStatus", "GinLog"]
hooks_file="$BASE_DIR/lua/gin.lua"

# show diff from recover file
[[plugins]]
on_event=['SwapExists']
repo="chrisbra/Recover.vim"

[[plugins]]
repo='phaazon/hop.nvim'
on_event = ["BufReadPre", "BufNewFile"]
hooks_file ="$BASE_DIR/lua/hop_config.lua"


[[plugins]]
repo='echasnovski/mini.diff'
on_event = ["BufReadPre", "BufNewFile"]
lua_source='''
require('mini.diff').setup()
'''

[[plugins]]
repo='akinsho/toggleterm.nvim'
on_map= {n = "<C-t>"}
lua_source='''
require("toggleterm").setup({  
  size = 100,
  open_mapping = [[<c-t>]],
  hide_numbers = true,
  shade_filetypes = {},
  shade_terminals = true,
  shading_factor = 2,
  start_in_insert = true,
  insert_mappings = true,
  persist_size = true,
  direction = 'float',
  close_on_exit = true,})
'''

[[plugins]]
repo = 'tani/dmacro.nvim'
on_map = { n = '<C-d>', i = '<C-d>' }
lua_source='''
vim.keymap.set({ "i", "n" }, '<C-d>', '<Plug>(dmacro-play-macro)<CR>')
'''

[[plugins]]
repo="andersevenrud/nvim_context_vt"
on_event = ["BufReadPre", "BufNewFile"]
depends='nvim-treesitter'
lua_source='''
require("nvim_context_vt").setup({
	min_rows=5
})
'''

[[plugins]]
repo = "terryma/vim-expand-region"
on_event = ["BufReadPre", "BufNewFile"]
hook_source= '''
let g:expand_region_text_objects = {
      \ 'iw'  :0,
      \ 'iW'  :0,
      \ 'i"'  :0,
      \ 'ia'  :0,
      \ 'i)'  :1,
      \ 'il'  :1,       
	  \ 'if'  :1, 
      \ 'af'  :1, 
      \ 'it'  :1, 
      \ 'ie'  :0, 
      \ }
'''

[[plugins]]
repo = "lambdalisue/vim-file-protocol"
on_event = ["BufReadPre", "BufNewFile"]

[[plugins]]
repo="lambdalisue/vim-gf-improved"
on_map = { n = 'g' }
on_source = '''
let g:gf_improved_no_mappings = 1

" Define your own mappings
nmap <Leader>gf <Plug>(gf-improved-gf)
nmap <Leader>gF <Plug>(gf-improved-gF)
'''

[[plugins]]
repo="skanehira/denops-silicon.vim"
on_cmd = "Silicon"
on_source = '''
let g:silicon_options = {
      \  'font': 'Cica',
      \  'no_line_number': v:false,
      \  'no_round_corner': v:true,
      \  'no_window_controls': v:true,
      \  'background_color': '#aaaaff',
      \  'line_offset': 1,
      \  'line_pad': 2,
      \  'pad_horiz': 80,
      \  'pad_vert': 100,
      \  'shadow_blur_radius': 0,
      \  'shadow_color': '#555555',
      \  'shadow_offset_x': 0,
      \  'shadow_offset_y': 0,
      \  'tab_width': 4,
      \  'theme': 'Solarized (dark)',
      \ }
'''

[[plugins]]
repo='b0o/incline.nvim'
on_event = ["BufReadPre", "BufNewFile"]
lua_source='''
require('incline').setup(
{
	render = function(props)
		local buffullname = vim.api.nvim_buf_get_name(props.buf)
		local bufname_t = vim.fn.fnamemodify(buffullname, ':t')
		local bufname = (bufname_t and bufname_t ~= '') and bufname_t or '[No Name]'
		-- optional devicon
        local devicon = { ' ' }
        local success, nvim_web_devicons = pcall(require, 'nvim-web-devicons')
		    if success then
		        local bufname_r = vim.fn.fnamemodify(buffullname, ':r')
		        local bufname_e = vim.fn.fnamemodify(buffullname, ':e')
		        local base = (bufname_r and bufname_r ~= '') and bufname_r or bufname
		        local ext = (bufname_e and bufname_e ~= '') and bufname_e or vim.fn.fnamemodify(base, ':t')
		        local ic, hl = nvim_web_devicons.get_icon(base, ext, { default = true })
		        devicon = {
		          ic,
		          ' ',
		          group = hl
		        }
		-- modified indicator
		local modified_icon = {}
			if vim.api.nvim_get_option_value('modified', { buf = props.buf, }) then
		 	  modified_icon = vim.tbl_extend('force', { '‚óè ' }, {guifg='#968c81'})
		 	end
		return {
          devicon,
          bufname,
          modified_icon,
		}
        end
	end
	}
)
'''

[[plugins]]
repo="monaqa/dial.nvim"
on_map = { n = '<C-a>',  i = '<C-a>',  v = '<C-a>' }
lua_source='''
vim.keymap.set("n", "<C-a>", function()
    require("dial.map").manipulate("increment", "normal")
end)
vim.keymap.set("n", "<C-x>", function()
    require("dial.map").manipulate("decrement", "normal")
end)
vim.keymap.set("n", "g<C-a>", function()
    require("dial.map").manipulate("increment", "gnormal")
end)
vim.keymap.set("n", "g<C-x>", function()
    require("dial.map").manipulate("decrement", "gnormal")
end)
vim.keymap.set("x", "<C-a>", function()
    require("dial.map").manipulate("increment", "visual")
end)
vim.keymap.set("x", "<C-x>", function()
    require("dial.map").manipulate("decrement", "visual")
end)
vim.keymap.set("x", "g<C-a>", function()
    require("dial.map").manipulate("increment", "gvisual")
end)
vim.keymap.set("x", "g<C-x>", function()
    require("dial.map").manipulate("decrement", "gvisual")
end)
'''

[[plugins]]
repo='anuvyklack/pretty-fold.nvim'
on_event = ["BufReadPre", "BufNewFile"]
lua_source='''
require('pretty-fold').setup()
'''

[[plugins]]
repo='norcalli/nvim-colorizer.lua'
on_event = ["BufReadPre", "BufNewFile"]
lua_source='''
require('colorizer').setup()
'''
