[[plugins]]
repo="catppuccin/nvim"
hook_add='''
colorscheme catppuccin
'''

# dot repeat
[[plugins]]
repo="tpope/vim-repeat"

# utility
[[plugins]]
repo="nvim-lua/plenary.nvim"

[[plugins]]
repo='nvim-tree/nvim-web-devicons'

[[plugins]]
repo="ethanholz/nvim-lastplace"
lua_add='''
require("nvim-lastplace").setup()
'''

[[plugins]]
repo="kevinhwang91/promise-async"
lua_add = '''
require('async')
'''

[[plugins]]
repo='kana/vim-textobj-user'

[[plugins]]
repo='kana/vim-textobj-entire'

[[plugins]]
repo='kana/vim-textobj-line'

